//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_blank_tile_H
#define METASPRITE_blank_tile_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define blank_tile_TILE_ORIGIN 0
#define blank_tile_TILE_W 8
#define blank_tile_TILE_H 8
#define blank_tile_WIDTH 8
#define blank_tile_HEIGHT 8
#define blank_tile_TILE_COUNT 1
#define blank_tile_PALETTE_COUNT 1
#define blank_tile_COLORS_PER_PALETTE 4
#define blank_tile_TOTAL_COLORS 4
#define blank_tile_PIVOT_X 4
#define blank_tile_PIVOT_Y 4
#define blank_tile_PIVOT_W 8
#define blank_tile_PIVOT_H 8
extern const metasprite_t* const blank_tile_metasprites[1];

BANKREF_EXTERN(blank_tile)

extern const palette_color_t blank_tile_palettes[4];
extern const uint8_t blank_tile_tiles[0];

#endif
