//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(blank_tile)

const palette_color_t blank_tile_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	
};

const uint8_t blank_tile_tiles[0] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,   // Row 1 to 4 (all blank)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00    // Row 5 to 8 (all blank)
};

const metasprite_t blank_tile_metasprite0[] = {
	METASPR_TERM
};

const metasprite_t* const blank_tile_metasprites[1] = {
	blank_tile_metasprite0
};
