//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(coin_sprite)

const palette_color_t coin_sprite_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(251,242, 54), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	
};

const uint8_t coin_sprite_tiles[16] = {
	0x00,0x18,0x18,0x66,
	0x3c,0x42,0x7e,0x81,
	0x7e,0x81,0x3c,0x42,
	0x18,0x66,0x00,0x18
	
};

const metasprite_t coin_sprite_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const coin_sprite_metasprites[1] = {
	coin_sprite_metasprite0
};
