//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cursor_sprite_H
#define METASPRITE_cursor_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cursor_sprite_TILE_ORIGIN 0
#define cursor_sprite_TILE_W 8
#define cursor_sprite_TILE_H 16
#define cursor_sprite_WIDTH 8
#define cursor_sprite_HEIGHT 16
#define cursor_sprite_TILE_COUNT 2
#define cursor_sprite_PALETTE_COUNT 1
#define cursor_sprite_COLORS_PER_PALETTE 4
#define cursor_sprite_TOTAL_COLORS 4
#define cursor_sprite_PIVOT_X 4
#define cursor_sprite_PIVOT_Y 8
#define cursor_sprite_PIVOT_W 8
#define cursor_sprite_PIVOT_H 16
extern const metasprite_t* const cursor_sprite_metasprites[1];

BANKREF_EXTERN(cursor_sprite)

extern const palette_color_t cursor_sprite_palettes[4];
extern const uint8_t cursor_sprite_tiles[32];

#endif
