//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(food_sprite)

const palette_color_t food_sprite_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(143, 86, 59), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	
};

const uint8_t food_sprite_tiles[16] = {
	0x00,0x00,0x00,0x18,
	0x18,0x24,0x3c,0x42,
	0x3c,0x42,0x18,0x24,
	0x00,0x18,0x00,0x00
	
};

const metasprite_t food_sprite_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(4)),
	METASPR_TERM
};

const metasprite_t* const food_sprite_metasprites[1] = {
	food_sprite_metasprite0
};
