//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(guppy_sprite)

const palette_color_t guppy_sprite_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(223,113, 38), RGB8( 50, 60, 57), RGB8(  0,  0,  0)
	
};

const uint8_t guppy_sprite_tiles[16] = {
	0x00,0x00,0x5c,0x5c,
	0xfa,0xa6,0xff,0x81,
	0xff,0x81,0xfe,0xa2,
	0x5c,0x5c,0x00,0x00
	
};

const metasprite_t guppy_sprite_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const guppy_sprite_metasprites[1] = {
	guppy_sprite_metasprite0
};
