//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_hungry_guppy_sprite_H
#define METASPRITE_hungry_guppy_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define hungry_guppy_sprite_TILE_ORIGIN 0
#define hungry_guppy_sprite_TILE_W 8
#define hungry_guppy_sprite_TILE_H 16
#define hungry_guppy_sprite_WIDTH 8
#define hungry_guppy_sprite_HEIGHT 16
#define hungry_guppy_sprite_TILE_COUNT 2
#define hungry_guppy_sprite_PALETTE_COUNT 1
#define hungry_guppy_sprite_COLORS_PER_PALETTE 4
#define hungry_guppy_sprite_TOTAL_COLORS 4
#define hungry_guppy_sprite_PIVOT_X 4
#define hungry_guppy_sprite_PIVOT_Y 8
#define hungry_guppy_sprite_PIVOT_W 8
#define hungry_guppy_sprite_PIVOT_H 16
extern const metasprite_t* const hungry_guppy_sprite_metasprites[1];

BANKREF_EXTERN(hungry_guppy_sprite)

extern const palette_color_t hungry_guppy_sprite_palettes[4];
extern const uint8_t hungry_guppy_sprite_tiles[32];

#endif
