//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(hungry_guppy_sprite)

const palette_color_t hungry_guppy_sprite_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(143,151, 74), RGB8( 50, 60, 57), RGB8(  0,  0,  0)
	
};

const uint8_t hungry_guppy_sprite_tiles[32] = {
	0x00,0x00,0x5c,0x5c,
	0xfa,0xa6,0xff,0x81,
	0xff,0x81,0xfe,0xa2,
	0x5c,0x5c,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t hungry_guppy_sprite_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, S_PAL(2)),
	METASPR_TERM
};

const metasprite_t* const hungry_guppy_sprite_metasprites[1] = {
	hungry_guppy_sprite_metasprite0
};
